### PR TITLE
Add update/install script for Ubuntu

### PR DESCRIPTION
**Pull request by Moini**
As discussed in the forums, as a temporary workaround for missing packages. 
Doesn't yet install embroider-modder.

### CODE REVIEW

**Comment by lexelby** [comment]
Thanks!  Looking good so far.  I'm wondering though, can you change it so that it doesn't say "Lexelby's embroidery extension" but instead just says "inkscape-embroidery extension" or the like?  I feel weird about it being referred to as "my" extension since other folks have contributed too.

Also, can we make a `bin/` directory and put the install script in there?

**Comment by Moini** [comment]
I was trying to find a way to differentiate this version from the others... I think I'll add a link to the github repo instead.
Of course, I'll move the file.

**Comment by Moini** [comment]
Done! Thank you for the review, Lex!

**Comment by Moini** [comment]
Currently testing this on a fresh 16.04 Ubuntu, doesn't work fully yet. wxpython has some extensive depency set! (and pip is actually python-pip)

**Comment by Moini** [comment]
Tested on a vanilla Ubuntu 16.04 in VirtualBox, takes very long due to compiling that wxpython, but seems to work (extension dialogs open, as far as I can test; libembroidery-convert prints out its help section).

**Comment by lexelby** [comment]
Looking great!  I think we can avoid building all of wxpython by just installing `python-wxgtk3.0` with apt.  That debian package includes the egg-info file that should convince `pip` it doesn't need to build and install `wxPython` to satisfy the `requirements.txt`.  That's how I set things up on my system.

**Comment by Moini** [comment]
Ah, cool. That's going to make installation a /tiny/ bit faster :) Will update the script.

**Comment by Moini** [comment]
Still need to sift through the dependencies that I can remove now.

**Comment by Moini** [comment]
Done. And tested on vanilla Ubuntu 16.04.

**Comment by Moini** [comment]
@lexelby Ready to merge - unless there's anything you want me to change?

**Comment by Moini** [comment]
Thanks, @lexelby !

**Pull request merged**
