### PR TITLE
remove uses of `wx.CB_SORT` to fix OS X

### LINKED ISSUE #7: Params not running properly
When I run the Embroidery extension:
Embroider..  works
Params gives me the following error:

Traceback (most recent call last):
  File "embroider_params.py", line 618, in <module>
    e.affect()
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "embroider_params.py", line 592, in effect
    frame = SettingsFrame(tabs_factory=self.create_tabs)
  File "embroider_params.py", line 316, in __init__
    self.preset_chooser = wx.ComboBox(self, wx.ID_ANY, style=wx.CB_SORT)
wxAssertionError: C++ assertion "!(style & wxCB_SORT)" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py27/Phoenix/ext/wxWidgets/src/osx/combobox_osx.cpp(60) in Create(): wxCB_SORT not currently supported by wxOSX/Cocoa

### PR DESCRIPTION
**Pull request by lexelby**
Should fix #7.

@jjohns3527 and @oscarminus, could one or both of you test this to see if it fixes the errors on OS X?

### CODE REVIEW

**Comment by oscarminus** [comment]
Yes it works. You can merge it.

Thank you

**Comment by jjohns3527** [comment]
Yes, it works.  

On a mac the file that is running is hidden in /.config/inkscape/extensions/embroider_params.py.  which can't be seen in the Finder or accessed with Xcode.  But editing it in a terminal worked!  

@lexelby Thanks very much!

**Comment by jjohns3527** [comment]
Sorry to take a while to get to this….busy time of year.  But I finally was able to find the embroider_params.py file that was running on my mac, and now the window works without crashing!!

Thanks again for your help and for the program.  It’s been invaluable to my project.  

I’ve been able to do the running stitches quite nicely, too, though that’s not what most people want from an embroidery machine.   Here’s a quick drawing of a chainlink fence in running stitches. Once I have some good photos I’ll post them to the site for other people’s reference. 

Jennifer



<II><II><II><II><II>

**Comment by lexelby** [comment]
Thanks for testing!

@jjohns3527 I'd also really love to see the picture of the final product after you've used the embroidered pieces to make impressions, if you're willing to share :)

**Pull request merged**
